### PR TITLE
New features

### PR DESCRIPTION
**Pull request by tipoman9**
1. Feedback from wfb concerning dropped packets, or failed injection. This leads to distorted video and is hard to track down. Now a nice message in the HUD will be displayed.
photo_2024-01-02_01-52-09
In order to make this work, wfb_tx output must be redirected to wfb_tx  [all the params]   2>&1 | tee -a /tmp/wfb.log &

2. Added support for SigmaStart temp sensor, so now  all FPV platforms will support Camera temp sensor via mavlink.  

3 Rotary switch better support. Now when you need to switch from position 1 to 5, all steps in between (2 or 3 or 4) may get executed. So added:
-p option is useful for rotary switches, where each switch step will generate a command till the desired one is reached. In order to avoid this, the channel value must be constant for a given period in order to be accepted, for example 1000ms. This way if you never stay more than a second on a step of the rotary switch while rotating it, only the last one will be accepted. The drawback is the delay this options adds.

### CODE REVIEW

**Comment by widgetii** [comment]
Is notes.txt file included by mistake? It seems it's a some localhost quick notes

**Comment by tipoman9** [comment]
Yes, these are instructions how to quickly cross-compile the code against an OpenIPC platform build locally for specific SoC and then copy the file to the cam. Maybe I need to add some more description like:

To compile for a specific camera, pull OpenIPC locally and compile it for the desired chipset.
If it is compiled in ```~/src/openipc```  , then mavfwd can be compiled and copied to cam with IP 192.168.1.88 like this:
```
cp mavfwd.c /home/home/src/openipc/output/build/mavfwd-220d30e118d26008e94445887a03d77ba73c2d29/
make -C /home/home/src/openipc/output/ mavfwd-rebuild
scp /home/home/src/openipc/output/build/mavfwd-220d30e118d26008e94445887a03d77ba73c2d29/mavfwd root@192.168.1.88:/usr/bin/
```

**Comment by widgetii** [comment]
What about moving it into main README? Otherwise, nobody finds the notes

**Comment by tipoman9** [comment]
Moved instructions to README and removed notes.txt.

**Comment by widgetii** [comment]
Thank you for your great work

**Pull request merged**
